name: finance
channels:
- base
- conda-forge
- anaconda
dependencies:
- python==3.9
# project tools
- jupyter
- python-dotenv # to collect environment variables
# basic ds tools
- matplotlib
- pandas
- scipy
- scikit-learn
- seaborn
- statsmodels
- pip
- pip:
    - PyYAML
    - yfinance
    - clean-text
    - unidecode

